"""Microcontroller-focused model export utilities.

The repo currently supports:
- Training sklearn artifacts (.pkl)
- Training YOLO detectors via Ultralytics (best-effort)
- Packaging deployments via Edge Impulse zip + optional ONNX/TFLite conversion

This module adds a targeted backend step:
1) Export/prepare a quantized TFLite model for microcontrollers (best-effort).
2) Generate C/C++ project skeleton files for popular MCUs.

Because full int8 conversion + C array generation depends heavily on the model type
(and available tooling), this implementation is defensive:
- If TFLite conversion tooling is missing, it creates a clear placeholder package.
- If conversion succeeds, it writes a quantized .tflite and a header skeleton.

Integration: expose a new Flask action in web_app.py: `export-mcu`.
"""

from __future__ import annotations

import json
import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, Optional


@dataclass
class ExportResult:
    ok: bool
    output_dir: Optional[str] = None
    artifacts: Optional[Dict[str, Any]] = None
    error: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        return {
            "ok": self.ok,
            "output_dir": self.output_dir,
            "artifacts": self.artifacts or {},
            "error": self.error,
        }


MCU_TEMPLATES: dict[str, dict[str, Any]] = {
    "arduino": {
        "display": "Arduino (TFLite Micro)",
        "files": [
            "README.md",
            "src/main.ino",
            "src/model_data.h",
            "src/labels.h",
            "src/model_data.cc",
        ],
    },
    "esp32": {
        "display": "ESP32 (TFLite Micro)",
        "files": [
            "README.md",
            "components/app/model_data.h",
            "components/app/main.cpp",
        ],
    },
    "stm32": {
        "display": "STM32 (CMSIS-NN - placeholder)",
        "files": [
            "README.md",
            "cmsis_nn_skeleton.c",
            "model_data.bin.placeholder",
        ],
    },
}


def _safe_copy_if_exists(src: Path, dst: Path) -> bool:
    if src.exists() and src.is_file():
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dst)
        return True
    return False


def _write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def generate_mcu_template(template_dir: Path, mcu: str) -> None:
    template = MCU_TEMPLATES.get(mcu)
    if not template:
        raise ValueError(f"Unsupported MCU target: {mcu}")

    # README
    readme = f"""# MCU Export Package ({mcu})\n\nThis package was generated by the IoT ML Studio backend.\n\n## Contents\n"""
    for f in template["files"]:
        readme += f"- {f}\n"

    readme += "\n\n## Notes\n- The actual int8 model array generation depends on model type and available tooling.\n- If you see placeholders, add TFLite Micro model header generation to your environment.\n"
    _write_text(template_dir / "README.md", readme)

    # Basic skeletons
    if mcu == "arduino":
        _write_text(
            template_dir / "src/main.ino",
            """#include <Arduino.h>\n\n// Placeholder for TensorFlow Lite Micro integration.\n// Upload model_data.h and labels.h next.\n\n#include "model_data.h"\n#include "labels.h"\n\nvoid setup() {\n  Serial.begin(115200);\n  delay(2000);\n  Serial.println("MCU model ready (placeholder)." );\n}\n\nvoid loop() {\n  // TODO: Acquire input data, run inference, print results.\n  delay(1000);\n}\n""",
        )
        _write_text(
            template_dir / "src/model_data.h",
            """// Placeholder.\n// Replace with real TFLite Micro flatbuffer header when model export tooling is available.\n\n#pragma once\n\nextern const unsigned char model_data[];\nextern const unsigned int model_data_len;\n""",
        )
        _write_text(
            template_dir / "src/labels.h",
            """// Placeholder labels.\n#pragma once\nconst char* LABELS[] = {\n  \"0\",\n  \"1\",\n};\nconst int LABELS_COUNT = 2;\n""",
        )
        _write_text(
            template_dir / "src/model_data.cc",
            """// Placeholder implementation\n#include "model_data.h"\nconst unsigned char model_data[] = {0};\nconst unsigned int model_data_len = 1;\n""",
        )

    elif mcu == "esp32":
        _write_text(
            template_dir / "components/app/main.cpp",
            """#include <stdio.h>\n\n#include "model_data.h"\n\nint app_main() {\n  printf("ESP32 MCU model ready (placeholder).\\n");\n  // TODO: run TFLite Micro inference using model_data.\n  return 0;\n}\n""",
        )
        _write_text(
            template_dir / "components/app/model_data.h",
            """#pragma once\nextern const unsigned char model_data[];\nextern const unsigned int model_data_len;\n""",
        )

    elif mcu == "stm32":
        _write_text(
            template_dir / "cmsis_nn_skeleton.c",
            """// STM32 CMSIS-NN placeholder\n// TODO: Convert TFLite quantized model to CMSIS-NN format.\n#include <stdint.h>\n\nvoid cmsis_nn_infer_placeholder(const uint8_t* input, uint8_t* output) {\n  // placeholder\n  (void)input;\n  (void)output;\n}\n""",
        )
        _write_text(template_dir / "model_data.bin.placeholder", "PLACEHOLDER")


def export_quantized_tflite_for_microcontrollers(
    model_path: Path,
    out_tflite_path: Path,
    *,
    quantize_int8: bool = True,
) -> Dict[str, Any]:
    """Best-effort conversion to quantized TFLite.

    This repo mainly uses sklearn .pkl models and YOLO weights.
    True conversion to TFLite Micro requires specific export graphs.

    Strategy:
    - If a .tflite already exists adjacent to the model, copy it.
    - Otherwise attempt ONNX->TFLite conversion if .onnx exists.
    - Else return an error with clear messaging.
    """
    out_tflite_path.parent.mkdir(parents=True, exist_ok=True)

    # Adjacent .tflite
    if model_path.suffix.lower() != ".tflite":
        candidate = model_path.with_suffix(".tflite")
        if candidate.exists():
            shutil.copy2(candidate, out_tflite_path)
            return {"ok": True, "source": str(candidate), "copied": True}

    # Adjacent .onnx
    candidate_onnx = model_path.with_suffix(".onnx")
    if candidate_onnx.exists():
        try:
            import tensorflow as tf  # type: ignore
            import onnx  # type: ignore
            from onnx_tf.backend import prepare  # type: ignore

            onnx_model = onnx.load(str(candidate_onnx))
            tf_rep = prepare(onnx_model, strict=False)
            saved_dir = out_tflite_path.parent / "__tf_savedmodel"
            if saved_dir.exists():
                shutil.rmtree(saved_dir)
            saved_dir.mkdir(parents=True, exist_ok=True)
            tf_rep.export_graph(str(saved_dir))

            converter = tf.lite.TFLiteConverter.from_saved_model(str(saved_dir))
            if quantize_int8:
                converter.optimizations = [tf.lite.Optimize.DEFAULT]
                converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
            tflite_model = converter.convert()

            out_tflite_path.write_bytes(tflite_model)
            return {"ok": True, "source": str(candidate_onnx), "copied": False, "quantize_int8": quantize_int8}
        except Exception as e:
            return {"ok": False, "error": str(e), "attempt": "onnx->tflite"}

    return {"ok": False, "error": "No .tflite or .onnx found next to the model; cannot quantize/export automatically."}


def generate_cpp_code_for_microcontroller_from_tflite(
    tflite_path: Path,
    out_dir: Path,
    *,
    mcu: str,
) -> Dict[str, Any]:
    """Generate C/C++ placeholders + copy tflite.

    Real TFLite Micro header generation normally uses `xxd` + TFLite Micro scripts.
    Here we generate skeleton + copy the quantized tflite.
    """
    if not tflite_path.exists():
        return {"ok": False, "error": "tflite not found"}

    out_dir.mkdir(parents=True, exist_ok=True)
    # Copy model
    _safe_copy_if_exists(tflite_path, out_dir / tflite_path.name)

    generate_mcu_template(out_dir, mcu)
    return {"ok": True, "tflite_path": str(tflite_path), "out_dir": str(out_dir), "mcu": mcu}


def export_for_mcu_pipeline(
    model_path_text: str,
    *,
    mcu: str,
    output_dir_text: str,
    quantize_int8: bool = True,
) -> ExportResult:
    try:
        model_path = Path(model_path_text).expanduser()
        if not model_path.exists():
            return ExportResult(ok=False, error=f"Model not found: {model_path}")

        output_dir = Path(output_dir_text).expanduser()
        export_root = output_dir / f"mcu_export_{mcu}"
        export_root.mkdir(parents=True, exist_ok=True)

        # 1) quantized tflite
        tflite_out = export_root / "model_int8.tflite"
        q = export_quantized_tflite_for_microcontrollers(model_path, tflite_out, quantize_int8=quantize_int8)

        # 2) generate code skeleton
        cpp = generate_cpp_code_for_microcontroller_from_tflite(
            tflite_out if q.get("ok") else tflite_out,
            export_root / "firmware",
            mcu=mcu,
        )

        # 3) write export metadata
        meta = {
            "source_model": str(model_path),
            "mcu": mcu,
            "quantize_int8": quantize_int8,
            "tflite_conversion": q,
            "code_generation": cpp,
        }
        (export_root / "export_metadata.json").write_text(json.dumps(meta, indent=2), encoding="utf-8")

        ok = bool(q.get("ok"))
        return ExportResult(ok=ok, output_dir=str(export_root), artifacts={"tflite": str(tflite_out), "firmware_dir": str(export_root / "firmware")}).to_dict()  # type: ignore
    except Exception as e:
        return ExportResult(ok=False, error=str(e)).to_dict()  # type: ignore

